import importlib.util
import sys
from pathlib import Path

from config import version_compat as vc

SCRIPT_PATH = Path(__file__).resolve().parents[1] / "tools" / "update_block_versions.py"
SPEC = importlib.util.spec_from_file_location("update_block_versions", SCRIPT_PATH)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC is not None and SPEC.loader is not None
sys.modules[SPEC.name] = MODULE
SPEC.loader.exec_module(MODULE)


def test_attribute_first_versions_picks_earliest_appearance():
    registries = {
        2860: {"minecraft:stone", "minecraft:grass"},
        3105: {"minecraft:stone", "minecraft:grass", "minecraft:mud"},
        3698: {"minecraft:stone", "minecraft:short_grass", "minecraft:mud"},
    }
    first_seen, floor = MODULE.attribute_first_versions(registries)
    assert floor == 2860
    assert first_seen["minecraft:stone"] == 2860
    assert first_seen["minecraft:mud"] == 3105          # introduced 1.19
    assert first_seen["minecraft:short_grass"] == 3698  # renamed in 1.20.3


def test_write_blocks_json_omits_floor_blocks(tmp_path):
    first_seen = {
        "minecraft:stone": 2860,       # floor -> omitted (assumed 1.18-safe)
        "minecraft:mud": 3105,
        "minecraft:short_grass": 3698,
    }
    out = tmp_path / "block_versions.json"
    count = MODULE.write_blocks_json(first_seen, floor=2860, path=out)
    assert count == 2
    loaded = vc.load_block_versions_json(str(out))
    assert loaded == {"minecraft:mud": 3105, "minecraft:short_grass": 3698}
    assert "minecraft:stone" not in loaded


def test_write_releases_json_is_loadable_by_version_compat(tmp_path):
    releases = {3105: "1.19", 2860: "1.18"}
    out = tmp_path / "mc_versions.json"
    MODULE.write_releases_json(releases, out)
    assert vc.load_releases_json(str(out)) == (("1.18", 2860), ("1.19", 3105))


def test_generated_tables_drive_compatibility_end_to_end(tmp_path):
    # A block file generated by the tool should feed the same report logic.
    first_seen = {"minecraft:stone": 2860, "minecraft:pale_oak_planks": 4189}
    out = tmp_path / "block_versions.json"
    MODULE.write_blocks_json(first_seen, floor=2860, path=out)
    loaded = vc.load_block_versions_json(str(out))
    assert loaded["minecraft:pale_oak_planks"] == vc.data_version_for("1.21.4")
