"""Minecraft version / DataVersion compatibility helpers.

CityGen copies block strings straight from the source world into the output
Sponge schematic, so block *content* is version-transparent. What is not
transparent is:

* the ``DataVersion`` stamped on the schematic (WorldEdit upgrades an older
  schematic forward into a newer world, but cannot downgrade a newer one), and
* whether every block used by the assets actually *exists* in the target
  version (WorldEdit cannot conjure ``pale_oak_planks`` into a 1.18 world).

This module provides the curated release table, source-world detection, and the
"what is the real minimum compatible version for these blocks" computation. It
imports nothing from the rest of ``config`` so it can be used from
``config_world`` without an import cycle.

The export hard floor is Minecraft 1.19.4 (``HARD_FLOOR_DATA_VERSION``): the
bundled assets need 1.19.4 blocks (cherry wood, pink petals) and it is the oldest
target the Sponge v2 container still reaches, so older targets are refused. The
Anvil *reader* still accepts 1.18+ source worlds; the floor here governs the
export target, not the input. The release table and block-version map are loaded
from generated JSON shipped as package data (mc_versions.json,
block_versions.json); regenerate them with tools/update_block_versions.py when a
newer Minecraft release ships.
"""
from __future__ import annotations

import json
import os
from collections.abc import Iterable

import nbtlib

_CONFIG_DIR = os.path.dirname(os.path.abspath(__file__))
# Authoritative version data, generated by tools/update_block_versions.py and
# shipped as package data. Regenerate when a newer Minecraft release ships.
RELEASES_JSON_PATH = os.path.join(_CONFIG_DIR, "mc_versions.json")
BLOCK_VERSIONS_JSON_PATH = os.path.join(_CONFIG_DIR, "block_versions.json")


def load_releases_json(path):
    """Ordered (release, data_version) tuple from a JSON map, or None if unusable."""
    if not os.path.isfile(path):
        return None
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        rows = [
            (str(name), int(version))
            for name, version in data.items()
            if str(name).strip()
        ]
    except (OSError, ValueError, AttributeError):
        return None
    rows.sort(key=lambda item: item[1])
    return tuple(rows) or None


def load_block_versions_json(path):
    """Mapping of block id -> minimum DataVersion from a JSON map, or None if unusable."""
    if not os.path.isfile(path):
        return None
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        result = {
            str(block): int(version)
            for block, version in data.items()
            if str(block).strip()
        }
    except (OSError, ValueError, AttributeError):
        return None
    return result or None


def _require(loaded, path):
    if loaded is None:
        raise RuntimeError(
            f"Version data missing or unreadable: {path}\n"
            "Run `python tools/update_block_versions.py` to (re)generate it."
        )
    return loaded


# Backward-compatibility floor. Forward compat is free -- WorldEdit upgrades an
# older schematic forward into a newer world -- but backward is the hard
# direction, so we draw a hard line and refuse older targets. 1.19.4 is where the
# two binding constraints bottom out: the bundled assets need 1.19.4 blocks
# (cherry wood, pink petals), and it is the newest version still served by the
# Sponge v2 container that pre-1.20 WorldEdit (7.2.x) can read. Applied as a
# filter over the generated table, so it survives regeneration.
HARD_FLOOR_DATA_VERSION = 3337  # Minecraft 1.19.4

# Ordered Java Edition release -> DataVersion, loaded from shipped JSON and
# clamped to the hard floor: older releases are dropped from the table entirely,
# so they never surface in the version selector or in version resolution.
RELEASES: tuple[tuple[str, int], ...] = tuple(
    row
    for row in _require(load_releases_json(RELEASES_JSON_PATH), RELEASES_JSON_PATH)
    if row[1] >= HARD_FLOOR_DATA_VERSION
)
_NAME_TO_VERSION = dict(RELEASES)
# Lowest supported version (the hard floor) and the default target used when a
# source world's own DataVersion cannot be detected.
SUPPORTED_FLOOR = min(version for _, version in RELEASES)
FALLBACK_DATA_VERSION = max(version for _, version in RELEASES)

# Block id -> lowest DataVersion the block exists in.
BLOCK_MIN_DATA_VERSION: dict[str, int] = _require(
    load_block_versions_json(BLOCK_VERSIONS_JSON_PATH), BLOCK_VERSIONS_JSON_PATH
)


def data_version_for(release_name: str) -> int | None:
    """DataVersion for a known release name, or None if unknown."""
    return _NAME_TO_VERSION.get(release_name)


def release_name_for(data_version: int) -> str:
    """Human label for a DataVersion.

    Returns the exact release name when known, otherwise a descriptive
    approximation anchored to the newest release not exceeding it.
    """
    exact = next((name for name, ver in RELEASES if ver == data_version), None)
    if exact is not None:
        return exact
    below = [item for item in RELEASES if item[1] <= data_version]
    if not below:
        return f"pre-{RELEASES[0][0]} (DataVersion {data_version})"
    name, _ = below[-1]
    return f"{name}+ (DataVersion {data_version})"


def block_base_id(state: str) -> str:
    """Namespaced base block id from a block state or bare name."""
    name = str(state).split("[", 1)[0]
    return name if ":" in name else f"minecraft:{name}"


def block_min_data_version(state: str) -> int:
    """Lowest DataVersion in which this block exists under its current id."""
    return BLOCK_MIN_DATA_VERSION.get(block_base_id(state), SUPPORTED_FLOOR)


# Block renames: current id -> (previous id, DataVersion it was renamed at).
# Below the threshold the block must be written under its previous id to exist
# in the target version. Minecraft's DataFixer knows these, but they are not in
# the generated registry reports, so this short list is curated by hand.
BLOCK_RENAMES: dict[str, tuple[str, int]] = {
    "minecraft:short_grass": ("minecraft:grass", 3698),   # renamed in 1.20.3
    "minecraft:iron_chain": ("minecraft:chain", 4554),    # renamed in 1.21.9
}


def _oldest_rename_id(base: str) -> str:
    """Follow the rename chain to the earliest id this block ever had."""
    seen = set()
    while base in BLOCK_RENAMES and base not in seen:
        seen.add(base)
        base = BLOCK_RENAMES[base][0]
    return base


def downgrade_block(state: str, target_data_version: int) -> str:
    """Rewrite a block state to the id valid at ``target_data_version``.

    Walks the rename chain: for each id newer than the target, substitute its
    previous id (properties preserved). Returns the state unchanged when no
    rename applies, so this is a no-op for current-version targets.
    """
    state = str(state)
    head, sep, props = state.partition("[")
    base = head if ":" in head else f"minecraft:{head}"
    new_base = base
    while new_base in BLOCK_RENAMES and target_data_version < BLOCK_RENAMES[new_base][1]:
        new_base = BLOCK_RENAMES[new_base][0]
    if new_base == base:
        return state
    return new_base + (sep + props if sep else "")


def effective_min_data_version(state: str) -> int:
    """Lowest DataVersion this block can reach, accounting for renames.

    A renameable block can be written under an older id, so its effective floor
    is the introduction version of the earliest id in its rename chain.
    """
    return block_min_data_version(_oldest_rename_id(block_base_id(state)))


def min_compatible_data_version(states: Iterable[str]) -> int:
    """Lowest DataVersion that a schematic of these blocks can paste into.

    Uses the rename-aware floor: a block that can be downgraded to an older id
    does not raise the minimum. Paste into anything older than the returned
    version and at least one block would not exist under any id.
    """
    floor = SUPPORTED_FLOOR
    for state in states:
        version = effective_min_data_version(state)
        if version > floor:
            floor = version
    return floor


def compatibility_report(states: Iterable[str], target_data_version: int) -> dict:
    """Assess whether these blocks can paste into ``target_data_version``.

    A block newer than the target either has a rename to an older id (handled
    automatically on export, listed under ``renamed``) or genuinely does not
    exist there (``offending`` -- holes on paste). ``floor`` is the rename-aware
    minimum compatible version.
    """
    bases = {block_base_id(state) for state in states}
    floor = SUPPORTED_FLOOR
    offending, renamed = [], []
    for base in bases:
        eff = effective_min_data_version(base)
        floor = max(floor, eff)
        if block_min_data_version(base) > target_data_version:
            if eff <= target_data_version:
                renamed.append({"block": base, "as": downgrade_block(base, target_data_version)})
            else:
                offending.append(
                    {"block": base, "min_data_version": eff, "min_release": release_name_for(eff)}
                )
    offending.sort(key=lambda item: (-item["min_data_version"], item["block"]))
    renamed.sort(key=lambda item: item["block"])
    return {
        "target_data_version": target_data_version,
        "target_release": release_name_for(target_data_version),
        "floor_data_version": floor,
        "floor_release": release_name_for(floor),
        "ok": not offending,
        "offending": offending,
        "renamed": renamed,
    }


def detect_world_data_version(save_path: str) -> int | None:
    """Read ``Data.DataVersion`` from a world's ``level.dat``, or None.

    Authoritative for the source world's own version; no release table needed.
    Tolerant of a missing/unreadable file so a trimmed world falls back cleanly.
    """
    if not save_path:
        return None
    level_dat = os.path.join(save_path, "level.dat")
    if not os.path.isfile(level_dat):
        return None
    try:
        data = nbtlib.load(level_dat).get("Data")
        if data is None:
            return None
        version = data.get("DataVersion")
        return int(version) if version is not None else None
    except (OSError, KeyError, ValueError):
        return None
