"""Minecraft version / DataVersion helpers.

CityGen copies block strings straight from the source world into the output
Sponge schematic, so block *content* is version-transparent. The one thing that
is not transparent is the ``DataVersion`` stamped on the schematic: WorldEdit
upgrades an older schematic forward into a newer world, but cannot downgrade a
newer one.

CityGen therefore commits to *forward-only* compatibility. The export target is
always the source world's own version or newer (the version selector never offers
an older one) and is clamped up to the 1.19.4 hard floor
(``HARD_FLOOR_DATA_VERSION``): the bundled assets need 1.19.4 blocks (cherry
wood, pink petals) and it is the oldest target the Sponge v2 container still
reaches. Because the target is never older than any block in the palette, every
block is guaranteed to exist in it -- WorldEdit handles the forward upgrade for
free -- so there is no downgrade or "missing block" computation to do.

This module provides the curated release table, source-world detection, and
release-name labelling. It imports nothing from the rest of ``config`` so it can
be used from ``config_world`` without an import cycle. The release table is
loaded from generated JSON shipped as package data (mc_versions.json); regenerate
it with tools/update_mc_versions.py when a newer Minecraft release ships.
"""
from __future__ import annotations

import json
import os

import nbtlib

_CONFIG_DIR = os.path.dirname(os.path.abspath(__file__))
# Authoritative release table, generated by tools/update_mc_versions.py and
# shipped as package data. Regenerate when a newer Minecraft release ships.
RELEASES_JSON_PATH = os.path.join(_CONFIG_DIR, "mc_versions.json")


def load_releases_json(path):
    """Ordered (release, data_version) tuple from a JSON map, or None if unusable."""
    if not os.path.isfile(path):
        return None
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        rows = [
            (str(name), int(version))
            for name, version in data.items()
            if str(name).strip()
        ]
    except (OSError, ValueError, AttributeError):
        return None
    rows.sort(key=lambda item: item[1])
    return tuple(rows) or None


def _require(loaded, path):
    if loaded is None:
        raise RuntimeError(
            f"Version data missing or unreadable: {path}\n"
            "Run `python tools/update_mc_versions.py` to (re)generate it."
        )
    return loaded


# Forward-only compatibility floor. Forward compat is free -- WorldEdit upgrades
# an older schematic forward into a newer world -- but backward is impossible, so
# we draw a hard line and refuse older targets. 1.19.4 is where the two binding
# constraints bottom out: the bundled assets need 1.19.4 blocks (cherry wood,
# pink petals), and it is the newest version still served by the Sponge v2
# container that pre-1.20 WorldEdit (7.2.x) can read. Applied as a filter over
# the generated table, so it survives regeneration.
HARD_FLOOR_DATA_VERSION = 3337  # Minecraft 1.19.4

# Ordered Java Edition release -> DataVersion, loaded from shipped JSON and
# clamped to the hard floor: older releases are dropped from the table entirely,
# so they never surface in the version selector or in version resolution.
RELEASES: tuple[tuple[str, int], ...] = tuple(
    row
    for row in _require(load_releases_json(RELEASES_JSON_PATH), RELEASES_JSON_PATH)
    if row[1] >= HARD_FLOOR_DATA_VERSION
)
_NAME_TO_VERSION = dict(RELEASES)
# Lowest supported version (the hard floor) and the default target used when a
# source world's own DataVersion cannot be detected.
SUPPORTED_FLOOR = min(version for _, version in RELEASES)
FALLBACK_DATA_VERSION = max(version for _, version in RELEASES)


def data_version_for(release_name: str) -> int | None:
    """DataVersion for a known release name, or None if unknown."""
    return _NAME_TO_VERSION.get(release_name)


def release_name_for(data_version: int) -> str:
    """Human label for a DataVersion.

    Returns the exact release name when known, otherwise a descriptive
    approximation anchored to the newest release not exceeding it.
    """
    exact = next((name for name, ver in RELEASES if ver == data_version), None)
    if exact is not None:
        return exact
    below = [item for item in RELEASES if item[1] <= data_version]
    if not below:
        return f"pre-{RELEASES[0][0]} (DataVersion {data_version})"
    name, _ = below[-1]
    return f"{name}+ (DataVersion {data_version})"


def detect_world_data_version(save_path: str) -> int | None:
    """Read ``Data.DataVersion`` from a world's ``level.dat``, or None.

    Authoritative for the source world's own version; no release table needed.
    Tolerant of a missing/unreadable file so a trimmed world falls back cleanly.
    """
    if not save_path:
        return None
    level_dat = os.path.join(save_path, "level.dat")
    if not os.path.isfile(level_dat):
        return None
    try:
        data = nbtlib.load(level_dat).get("Data")
        if data is None:
            return None
        version = data.get("DataVersion")
        return int(version) if version is not None else None
    except (OSError, KeyError, ValueError):
        return None
